version: '3.9'
services:
  ratingapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: start:prod
    restart: always
    environment:
      - NODE_ENV=prod
      - PRODUCTION_MONGO_URL=mongodb://admin:admin@mongo:27017/admin
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
